### ISSUE TITLE
Add License Header to files

### ISSUE THREAD

**Issue by ramymagdy** [neil-justice/louvain#1]
We are interested in using your implementation in our project, yet we cannot include it without proper License document and license headers per files.

**Comment by neil-justice** [comment]
Thanks for your interest!  I've added a license to the project.  I don't really have time to add a license header to every file but if you really need that, put together a pull request and I'll merge it.

**Comment by yelghare** [comment]
Hi Neil, thanks a lot for adding a license to the project. I added the license header to all Java files and created the pull request.

**Comment by neil-justice** [comment]
No worries!
