### ISSUE TITLE
Details of implementation.

### ISSUE THREAD

**Issue by isabelcpv** [neil-justice/louvain#4]
Hi, 
Can you provide more information about your implementation of Lovain's method?
In your G.java:

This creates the layered community structure cs from the spreedsheet twitter.csv:
```
    Graph g = new GraphBuilder().fromFile("graphs/twitter.csv", true);
    LouvainDetector ld = new LouvainDetector(g);
    LayeredCommunityStructure cs = new LayeredCommunityStructure(ld.run());
```

Then, this is another structure irr that was created with Infomap
```
    InfomapResultsReader irr = new InfomapResultsReader("graphs/infomap.tree");
    LayeredCommunityStructure cs2 = new LayeredCommunityStructure(irr.run());
```
  
and here these two layered communities are processed somehow. Can you clarify this part?
```
    // for (int i = 0; i < cs.layers(); i++) {
    //   for (int j = 0; j < cs2.layers(); j++) {
    //     System.out.printf("%.03f ", NMI.NMI(cs.layer(i), cs2.layer(j)));
    //   }
    //   System.out.println();
    // }
```

Thank you in advance!

**Comment by neil-justice** [comment]
Hi,

Thank you for your interest!

The G class is really just meant as an example of use.  As you've seen it creates two different layered community structures.

The commented out block would then compare the [normalised mutual information](https://en.wikipedia.org/wiki/Mutual_information) of each layer of the two community structures, which is functioning as a measurement of the similarity of the different community structures. If the two community structures are exactly the same the NMI would be 1.

I hope that has answered your question, if you have any other questions please ask.

**Comment by isabelcpv** [comment]
Hi, 

Thanks for the quick reply!

Is it possible to recover the community members in the current implementation?

**Comment by neil-justice** [comment]
No worries!

It's been a while since I looked at it but you should be able to pass the result of any implementation of Clusterer to the PartitionWriter to output to CSV.  Or you can use the LouvainSelector class which will output to CSV the highest modularity run of a given number of applications of the LouvainDetector.

**Comment by isabelcpv** [comment]
I will try that
Thank you!

**Comment by neil-justice** [comment]
Yes, you are correct about the output.  Each column after the first is the community that the node belongs to in a different layer.

After the LouvainDetector has finished running, it will have an internal list of graphs (the field is called graphs), the last one of which is the reduced network you want.  I didn't need this information for my  project so you will need to add a public getter method for that list if you need to access it.  Hope that helps!

**Comment by isabelcpv** [comment]
I will do that.
Thanks again Neil!
